trigger:
- main  # Runs the pipeline when the main branch is updated

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux VM to run Docker

stages:
- stage: SecurityScan
  displayName: "Run OWASP ZAP Scan"
  jobs:
  - job: Run_ZAP
    steps:
    
    - task: Bash@3
      displayName: 'Pull ZAP Docker Image'
      script: |
        docker pull owasp/zap2docker-stable

    - task: Bash@3
      displayName: 'Run OWASP ZAP Scan'
      script: |
        docker run --rm -v $(System.DefaultWorkingDirectory):/zap/wrk/ \
        owasp/zap2docker-stable zap-full-scan.py -t http://testphp.vulnweb.com/ -r zap_report.html

    - task: PublishBuildArtifacts@1
      displayName: 'Upload ZAP Report'
      inputs:
        pathToPublish: 'zap_report.html'
        artifactName: 'ZAP_Report'
